# Generated by Django 5.1.2 on 2024-10-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_last_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_active',
        ),
    ]
