# Generated by Django 5.1.2 on 2024-10-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usernotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
