# Generated by Django 5.1.2 on 2024-10-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EsportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('team_name', models.CharField(max_length=200)),
                ('opponent_name', models.CharField(max_length=200)),
                ('sport', models.CharField(max_length=10)),
                ('stat_type', models.CharField(max_length=50)),
                ('prizepick', models.FloatField()),
                ('underdog', models.FloatField()),
                ('projection_string', models.CharField(max_length=200)),
                ('difference', models.FloatField()),
                ('difference_percentage', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
